### ISSUE TITLE
Refactor Config Variables

### ISSUE THREAD

**Issue by AbhayAysola** [Keysign-Wallet/TNB-BOT#4]
Currently the config values are either hardcoded or stored in a seperate file. This is not easy for contributors since they would have to change back the values everytime they commit. You could simple use environment variables like via `os.environ.get(value)` or use a seperate `.env` file using a package like [python-dotenv](https://pypi.org/project/python-dotenv/) instead of the current setup.

**Comment by FilterUnfiltered** [comment]
Makes sense, but I personally have no experience with things like that. If you want you can have a go at it. I'll assign you.

**Comment by AbhayAysola** [comment]
> Makes sense, but I personally have no experience with things like that. If you want you can have a go at it. I'll assign you.

Sure! I'll work on it :)
