### ISSUE TITLE
Ugly messages, use embeds

### ISSUE THREAD

**Issue by FilterUnfiltered** [Keysign-Wallet/TNB-BOT#7]
The messages are ugly right now, so it is now @AbhayAysola's job to fix that in any way he can, primarily by using embeds (to their full extent, not just embedding the message :))

**Comment by AbhayAysola** [comment]
> The messages are ugly right now, so it is now @AbhayAysola's job to fix that in any way he can, primarily by using embeds (to their full extent, not just embedding the message :))

On it!

**Comment by FilterUnfiltered** [comment]
Fixed
